### ISSUE TITLE
Problem on bio/link github account

### ISSUE THREAD

**Issue by arnaud-zg** [remirobert/remirobert.github.io#1]
<img width="177" alt="screen shot 2016-10-25 at 11 30 56" src="https://cloud.githubusercontent.com/assets/10991546/19680581/93033920-9aa6-11e6-86cf-5c7a45229470.png">

It should be remirobert.github.io :+1:

**Comment by remirobert** [comment]
awwww yes thanks

**Comment by remirobert** [comment]
fixed
